name = "fast-filament"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"
binding = "ASSETS"
[[d1_databases]]
binding = "DB"
database_name = "plataforma"
database_id = "9f13bd3f-ee85-4001-81d7-ac9cd90ef241"
migrations_dir = "drizzle"
